### PR TITLE
Minor tutorial fixes/changes

### PR DESCRIPTION
**Pull request by nightmarebadger**
Went through the tutorial again to make sure there are no problems with it (there were some minor ones but nothing serious). Also made sure we use consistent style/wording/conventions

### CODE REVIEW

**Comment by disko** [comment]
First of all: thanks for going over it again!

We switched to "Semantic Linefeeds" (http://rhodesmill.org/brandon/2012/one-sentence-per-line/) for the docs recently. Makes editing and especially reading diffs in PRs much easier. Could you please re-add this (I guess reverting the change won't work?)?

**Comment by nightmarebadger** [comment]
Makes sense :)

Most of the work was done in the first commit (the actual problems), the second commit just changed the wording here and there to be consistent so it shouldn't be a problem. I'll go through it in the evening and update the PR.

**Comment by nightmarebadger** [comment]
Reverted the 80 line limit changes so it should be easier to go through it now :)

**Comment by disko** [comment]
Great, thanks a lot!

**Pull request merged**
