### PR TITLE
Http not found view

### PR DESCRIPTION
**Pull request by mgrbyte**
@disko @davidemoro

First stab at implementing #459.
Since this is my first PR of substance, I expect there may be one or two things not quite to your liking.
It turned out to be more complex that I first thought, particularly getting browser doc-tests working)

Summary
-------------
 * Added a specific browser test case for HTTPNotFound views.
 * `kotti.security.get_user` uses `unauthenticated_userid` to look up the user in the db.
 * `kotti.resources.Node` now formally implements `pyramid.interfaces.ILocation`, which provides
   a clean way to test if a context can be used in templates, `kotti.templates.TemplateAPI` methods (e.g `url`) and especially in tests.
   Mock/stub objects used as placeholders for`context` must implement ILocation.

### CODE REVIEW

**Comment by mgrbyte** [comment]
@davidemoro @disko
In particular I've not used the `i18n.sh` script in this PR - I'm not sure what to do with its output. 
It produces lots of untranslated strings that I have no domain knowledge/tool (besides google translate!)

**Comment by disko** [comment]
On 29 Sep 2015, at 3:25, Matt Russell wrote:

> I've not used the `i18n.sh` script in this PR

Please just run it and include at least the updated .pot and .po files 
in the PR.

**Comment by mgrbyte** [comment]
@disko let me know if there's anything more I can do here

**Comment by disko** [comment]
@mgrbyte Sorry for getting back so late on this.  Could you please rebase the branch, so that it can be merged?  TIA!

**Comment by disko** [comment]
Great job, thanks a lot.  Now add a line to ``CHANGES.txt`` and we're good to merge :).  

(please append ``[ci skip]`` to the commit message to not trigger a new Travis build)

**Pull request merged**
