### PR TITLE
Improve Code quality

### PR DESCRIPTION
**Pull request by teixas**
I have fixed``upload.js`` only. Codacy reports bad styling on python files like long lines which we ignore on existing pep8 rules.

### CODE REVIEW

**Comment by disko** [comment]
Does anyone use the "features" in ``kotti,js`` at all? Kotti itself doesn't and I'd say: let's (finally) get rid of it completely!  

If someone *does* use it in their code, we must not change ``dom_changed_handlers`` to ``domChangedHandlers`` as it would be an incompatible API change.

@dnouri: comment requested.

**Comment by teixas** [comment]
Nice point! But let's see if we should get rid of it or not...

**Comment by dnouri** [comment]
Fine with me to get rid of it.

**Comment by disko** [comment]
Thanks!

**Pull request merged**
