### PR TITLE
Add audit log support to Kotti.

### PR DESCRIPTION
**Pull request by b4oshany**
# Feature Support

  - The content audit log for editors to find content based on creation or
    modification.
  - Each content node has an audit log that displays all children of that
    node.
  - Content filtering and sorting by title, content type, container
    title, modification\_date and creation\_date
  - Content search

# Example

Audit Log for
Kotti

### CODE REVIEW

**Comment by disko** [comment]
This looks very cool, but why would it be necessary to include it in Kotti instead of "just" being an add on?

**Comment by b4oshany** [comment]
> This looks very cool, but why would it be necessary to include it in Kotti instead of "just" being an add on?

Well, the simple answer is, as the core of Kotti CMS and a means of creating and managing hierarchical data models, it's a great tool to find and filter data, especially for recently updated or created content and data models.

A changelog, audit log, site content log or whichever term or phrases it is deemed to me; it tends to be a standard feature and excellent selling point for robust content/data-driven system. Assuming that there is a large number of Kotti sites that are using the CMS feature will result in a large number of manual inclusion of this tool, well, that's if developers know about it. Therefore, having a tool like this built-in, instead of manually adding it on each Kotti instance, well, to me, that's a win.

**Comment by b4oshany** [comment]
> This looks very cool, but why would it be necessary to include it in Kotti instead of "just" being an add on?

Furthermore, this project is one step towards building another addon that would work similarly to [Plone's collection content type.](https://docs.plone.org/develop/plone/functionality/collections.html) The Plone like-collection addon will utilize the audit API endpoint that is apart of Kotti core to find and filter content while being able to create a content-based stored query. The same is said for other add-ons that require a built-in API to find and display content.

**Comment by castaf** [comment]
It is a very cool feature ! But for me, I consider Kotti more like a framework, and I prefer manage features trough addons.

**Comment by b4oshany** [comment]
> It is a very cool feature ! But for me, I consider Kotti more like a framework, and I prefer manage features trough addons.

Ok... In that case, can you create another org on Github, which fork or have a repository/add-on for kotti? Yes, I probably can search for stuff start with kotti_, but at times that is not enough.

**Comment by disko** [comment]
@b4oshany Sorry for the late replay – I'm drowning in work ATM.

I just sent you an invitation to join the ``kotti-collective`` team, which grants you the permission to create projects within the Kotti organization on Github. Feel free to move your ``kotti_`` projects there!

**Pull request closed without merging**
