### PR TITLE
Updated the copyright year

### PR DESCRIPTION
**Pull request by IonicaBizau**
Making my yearly contribution to Kotti. 😁 Keep up the good work!

/cc #306 #368 #483

### CODE REVIEW

**Comment by teixas** [comment]
What about using something dynamic? Like:

<tal:current-year define="date import:datetime.date">${date.today().year}</tal:current-year>

**Comment by IonicaBizau** [comment]
@teixas I was thinking there should be something like that. That's in the `pt` file, right? I'm not too familiar with Python, tho...

**Comment by teixas** [comment]
@IonicaBizau Exactly! Just copy/paste this snippet on both page templates

**Comment by IonicaBizau** [comment]
@teixas Thanks, just did! Not sure which template is the other one...

**Comment by teixas** [comment]
@IonicaBizau Ah sorry! Didn't notice that copyright file **isn't** a page template.
So COPYRIGHT.txt needs to be updated every year :)

**Comment by disko** [comment]
Happy New Year! ;-)

**Comment by IonicaBizau** [comment]
Yay! Happy new year! :grin: :tada: :fireworks:

**Pull request merged**
