### PR TITLE
README.rst: Add instructions for Docker

### PR DESCRIPTION
**Pull request by msabramo**
These steps worked for me using docker-osx on OS X 10.9.5. 

In theory, they should work anywhere.

### CODE REVIEW

**Comment by disko** [comment]
Can we move that to ``docs/first_steps/installation.rst`` instead?

**Comment by msabramo** [comment]
Done!

**Comment by disko** [comment]
Thanks!

**Comment by msabramo** [comment]
Cool! I don't see the new content yet on readthedocs. Is that because it's in the queue and takes some time or does it need to be manually told to rebuild?

**Comment by disko** [comment]
It's because we configured RTD to not build master as the default (intentionally).  Actually it was configured to not build master at all, but I just changed that.

**Pull request merged**
