### PR TITLE
Reduce db queries

### PR DESCRIPTION
**Pull request by disko**
This supersedes #448 snd #449 (same implementation, cleaned up commits)

### CODE REVIEW

**Comment by dnouri** [comment]
Looks good!

**Comment by disko** [comment]
Except for the still failing test on PostgreSQL "caused" by that change: https://github.com/disko/Kotti/commit/1efb1345e7a9412c6a0e746ca864de8b99c9b30a#diff-090c6d6f97cd0028f14840e7b7f6aa94R227 :(

**Comment by mgrbyte** [comment]
@disko I'd like to help get this one passing, can you ping me instructions on how you're running the test suite against postgres pls?
I've just checkout this branch and run:

```bash
mkvirtualenv reduce-db-queries
python setup.py dev
pip install psycopg2
createdb -T template0 -E UTF8 -O mattr kotti
KOTTI_TEST_DB_STRING="postgresql+psycopg2://mattr@/kotti" py.test
```
fwiw, I get one failure with the above:
/home/mattr/git/kotti/kotti/tests/browser.txt:548: DocTestFailure

**Comment by disko** [comment]
@mgrbyte this is exactly what I'm running and also the exact same failure.  The failure occurs with ``index=True`` on ``Node.parent_id`` and vanishes without.  

This makes absolutely no sense to me.  I've removed that single assert in 66b285fb50ac766387863c40de1eb9f43374370e and the test suite passes again on all environments.  Tbh: I'm tempted to leave it removed and merge the branch…

**Comment by mgrbyte** [comment]
@disko I think I solved it (maybe)

I think the test might be selecting the wrong control?

Line 548, insert:
  >>> import pdb;pdb.set_trace()
check the values of:
 browser.getLink('Make Public', index=0)
browser.getLink('Make Public', index=1)
browser.getLink('Make Public', index=2)

The current test uses the control with `index=2`
I changed it to `index=1` and the test passed.

**Comment by disko** [comment]
On 26 Sep 2015, at 22:15, Matt Russell wrote:

> @disko I think I solved it (maybe)
>
> I think the test might be selecting the wrong control?
>
> Line 548, insert:
> >>> import pdb;pdb.set_trace()
> check the values of:
> browser.getLink('Make Public', index=0)
> browser.getLink('Make Public', index=1)
> browser.getLink('Make Public', index=2)
>
> The current test uses the control with `index=2`
> I changed it to `index=1` and the test passed.

I tried that, too.  Unfortunately the test fails on MySQL and SQLite 
then… :(

**Comment by mgrbyte** [comment]
@disko I think its something do with the order of test execution not being the same.
Under SQLite:
```
(Pdb) browser.getLink('Make Public', index=0)
<Link text='Make Public' url='http://localhost:6543/second-child-1/@@workflow-change?new_state=public'>
(Pdb) browser.getLink('Make Public', index=1)
<Link text='Make Public' url='http://localhost:6543/second-child-1/third-child/@@workflow-change?new_state=public'>
(Pdb) browser.getLink('Make Public', index=2)
<Link text='Make Public' url='http://localhost:6543/second-child-1/grandchild-3/@@workflow-change?new_state=public'>
```
Under PostgreSQL:
```
<Link text='Make Public' url='http://localhost:6543/second-child-1/@@workflow-change?new_state=public'>
(Pdb) browser.getLink('Make Public', index=1)
<Link text='Make Public' url='http://localhost:6543/second-child-1/grandchild-2/@@workflow-change?new_state=public'>
(Pdb) browser.getLink('Make Public', index=2)
<Link text='Make Public' url='http://localhost:6543/second-child-1/grandchild-3/@@workflow-change?new_state=public'>
```

It would seem that either:
 - the order of links of the page are different due to some db ordering
 - the order of the tests executed by the test runner are different

**Comment by mgrbyte** [comment]
@disko 
I ran the test under both sqlite and pg backends again, writing out `browser.contents` to a file before the problematic call to `browser.getLink('Make Public', index=2)`.

The order of the rows is different, so I conclude that the ordering @@contents view changes depending on db backend.

To test this theory out, I dug around the code a bit.
Change Line 548 in browser.txt to use index=3
and
```
diff --git a/kotti/resources.py b/kotti/resources.py
index 22f32fe..f9762e7 100644
--- a/kotti/resources.py
+++ b/kotti/resources.py
@@ -247,7 +247,7 @@ class Node(Base, ContainerMixin, PersistentACLMixin):
         remote_side=[id],
         backref=backref(
             '_children',
-            collection_class=ordering_list('position'),
+            collection_class=ordering_list('position', reorder_on_append=True),
             order_by=[position],
             cascade='all',
         )
 ```
That makes the test pass on both backends (and @@contents is order the same for both back-ends)

See the [docstring](http://docs.sqlalchemy.org/en/latest/orm/extensions/orderinglist.html#sqlalchemy.ext.orderinglist.OrderingList.params.reorder_on_append) for sqlalchemy.ext.orderinglist.

**Comment by mgrbyte** [comment]
Here's 2 HTML files written using `browser.contents` before line 548  in browser.txt,
with `reorder_on_append` passed to `_children`'s collection class (passing):

browser-pass-sqlite
browser-pass-pg

and without (failures):

browser-fail-sqlite
browser-fail-pg

**Comment by mgrbyte** [comment]
fwiw, the whole test suite passes under both sqlite and pg with the reorder_on_append added.
:+1:  for merging it either way!

**Comment by disko** [comment]
@mgrbyte you da man!  thanks so much!

**Pull request merged**
